# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChoiceDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, uic
from PyQt5.QtWidgets import QLabel, QPlainTextEdit, QPushButton, QMainWindow
import QtDesigner


class dialogWindow(QtWidgets.QDialog):
    def __init__(self,parent = None, type_of_diff = '-', string_list = [''], _mainWindow = None):
        super(dialogWindow,self).__init__(parent, QtCore.Qt.WindowCloseButtonHint) # add this to remove --> '?' in title bar
        
        self._mainWindow = _mainWindow

        #Load file starting from Current working directory
        uic.loadUi("Main/UI Files//ChoiceDialog.ui", self)   # moved the files to two folders
  
        #Load widgets
        self.label_explanation = self.findChild(QLabel,"label_explanation")
        self.textBox = self.findChild(QPlainTextEdit, "TextBox")
        
      

        if type_of_diff == '-':
            self.label_explanation.setText('The following text exists in file A, but not in file B.')
        elif type_of_diff == '+':
            self.label_explanation.setText('The following text exists in the file B, but not in file A.')
        else:
            self.label_explanation.setText('Someting went wrong :(')

        #set text
        text = '\n'.join(string_list)
        self.textBox.setPlainText(text) 
        

        self.btnAdd = self.findChild(QPushButton,"btnAdd")
        self.btnSkip = self.findChild(QPushButton,"btnSkip")
        self.btnAutoComplete_A = self.findChild(QPushButton,"btnAutoComplete_A")
        self.btnAutoComplete_B = self.findChild(QPushButton, "btnAutoComplete_B")   
         
        if _mainWindow != None:
            # assigning functions to buttons
            self.btnAdd.clicked.connect(lambda: self.Add())
            self.btnSkip.clicked.connect(lambda: self.Skip())
            self.btnAutoComplete_A.clicked.connect(lambda: self.AutoComplete_A())
            self.btnAutoComplete_B.clicked.connect(lambda: self.AutoComplete_B())
        else:
            self.label_explanation.setText("This window isn't meant to be activated this way!")


        # self.show()
        

    def Add(self):      
        # self._mainWindow.labelA.setText('Test Add...')
        self._mainWindow._dialog_answer = 'Add'
        self.hide()

    def Skip(self):
        # self._mainWindow.labelB.setText('Test Skip...')
        self._mainWindow._dialog_answer = 'Skip'
        self.hide()

    def AutoComplete_A(self):
        # self._mainWindow.labelA.setText('Auto complete A...')
        self._mainWindow._dialog_answer = 'Auto-complete from A'
        self.hide()

    def AutoComplete_B(self):
        # self._mainWindow.labelB.setText('Auto complete B...')
        self._mainWindow._dialog_answer = 'Auto-complete from B'
        self.hide()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = dialogWindow()  
    # dialogWindow.window = dialogWindow()
    window.show()

    sys.exit(app.exec_())