# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\ergo2\Desktop\test\tekst.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1785, 826)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textA = QtWidgets.QTextEdit(self.centralwidget)
        self.textA.setGeometry(QtCore.QRect(10, 50, 551, 621))
        self.textA.setReadOnly(True)
        self.textA.setObjectName("textA")
        self.textB = QtWidgets.QTextEdit(self.centralwidget)
        self.textB.setGeometry(QtCore.QRect(580, 50, 551, 621))
        self.textB.setReadOnly(True)
        self.textB.setObjectName("textB")
        self.labelA = QtWidgets.QLabel(self.centralwidget)
        self.labelA.setGeometry(QtCore.QRect(10, 15, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelA.setFont(font)
        self.labelA.setObjectName("labelA")
        self.labelB = QtWidgets.QLabel(self.centralwidget)
        self.labelB.setGeometry(QtCore.QRect(580, 20, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelB.setFont(font)
        self.labelB.setObjectName("labelB")
        self.pb_A = QtWidgets.QPushButton(self.centralwidget)
        self.pb_A.setGeometry(QtCore.QRect(430, 20, 131, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pb_A.setFont(font)
        self.pb_A.setObjectName("pb_A")
        self.pb_B = QtWidgets.QPushButton(self.centralwidget)
        self.pb_B.setGeometry(QtCore.QRect(1000, 20, 131, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pb_B.setFont(font)
        self.pb_B.setObjectName("pb_B")
        self.pb_Compare = QtWidgets.QPushButton(self.centralwidget)
        self.pb_Compare.setGeometry(QtCore.QRect(10, 680, 1121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pb_Compare.setFont(font)
        self.pb_Compare.setObjectName("pb_Compare")
        self.textC = QtWidgets.QTextEdit(self.centralwidget)
        self.textC.setGeometry(QtCore.QRect(1150, 50, 551, 621))
        self.textC.setReadOnly(True)
        self.textC.setObjectName("textC")
        self.labelC = QtWidgets.QLabel(self.centralwidget)
        self.labelC.setGeometry(QtCore.QRect(1150, 20, 371, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelC.setFont(font)
        self.labelC.setObjectName("labelC")
        self.pb_C = QtWidgets.QPushButton(self.centralwidget)
        self.pb_C.setGeometry(QtCore.QRect(1150, 680, 551, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pb_C.setFont(font)
        self.pb_C.setObjectName("pb_C")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1785, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelA.setText(_translate("MainWindow", "Preview of text A"))
        self.labelB.setText(_translate("MainWindow", "Preview of text B"))
        self.pb_A.setText(_translate("MainWindow", "Browse"))
        self.pb_B.setText(_translate("MainWindow", "Browse"))
        self.pb_Compare.setText(_translate("MainWindow", "Compare"))
        self.labelC.setText(_translate("MainWindow", "Differences between text A and text B"))
        self.pb_C.setText(_translate("MainWindow", "Merge text A and text B"))
